# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdad55230f65591932df14e871a858be5dcb917e0b3aaf071f4d6a0b7666119797a9f1ae929235557dc818320d51e1062a5de3cff18b80274e9525a0c47b2b36

test:
  secret_key_base: 089ef51def044e9fa9f564962ac0490fa7a326530bc8090576908386a9bafefe62b155a5af6417889438df7444dfaea092468d06b0977c3594f4b0cb7d569ece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>